-- 1. Membuat database baru jika belum ada
CREATE DATABASE IF NOT EXISTS db_data_proyek;

-- 2. Menggunakan database yang baru dibuat
USE db_data_proyek;

-- 3. Membuat tabel PERTAMA: data_proyek_cr
CREATE TABLE IF NOT EXISTS data_proyek_cr (
    id VARCHAR(50) NOT NULL,
    timestamp DATETIME NOT NULL,
    cr_id VARCHAR(50) DEFAULT NULL,
    project_id VARCHAR(50) DEFAULT NULL,
    cr_date DATE DEFAULT NULL,
    requester_id VARCHAR(50) DEFAULT NULL,
    requester_role VARCHAR(50) DEFAULT NULL,
    change_category VARCHAR(50) DEFAULT NULL,
    change_type VARCHAR(50) DEFAULT NULL,
    change_trigger VARCHAR(50) DEFAULT NULL,
    change_description TEXT DEFAULT NULL,
    root_cause TEXT DEFAULT NULL,
    document_reference VARCHAR(255) DEFAULT NULL,
    document_link VARCHAR(255) DEFAULT NULL,
    wbs_code VARCHAR(50) DEFAULT NULL,
    activity_name VARCHAR(255) DEFAULT NULL,
    critical_path_status BOOLEAN DEFAULT NULL,
    bim_object_id VARCHAR(50) DEFAULT NULL,
    bim_element_name VARCHAR(50) DEFAULT NULL,
    object_location VARCHAR(50) DEFAULT NULL,
    risk_id VARCHAR(50) DEFAULT NULL,
    risk_category VARCHAR(50) DEFAULT NULL,
    risk_score_at_cr VARCHAR(50) DEFAULT NULL,
    estimated_time_impact_days INT DEFAULT NULL,
    estimated_cost_impact DECIMAL(21,2) DEFAULT NULL,
    quality_impact VARCHAR(50) DEFAULT NULL,
    risk_score_change INT DEFAULT NULL,
    affected_successors TEXT DEFAULT NULL,
    rework_potential VARCHAR(50) DEFAULT NULL,
    impact_summary TEXT DEFAULT NULL,
    system_recommendation TEXT DEFAULT NULL,
    alternative_actions TEXT DEFAULT NULL,
    priority_level VARCHAR(50) DEFAULT NULL,
    cr_status VARCHAR(50) DEFAULT NULL,
    approval_level VARCHAR(50) DEFAULT NULL,
    approval_decision VARCHAR(50) DEFAULT NULL,
    approval_notes TEXT DEFAULT NULL,
    approval_date DATE DEFAULT NULL,
    implementation_status VARCHAR(50) DEFAULT NULL,
    implementation_progress INT DEFAULT NULL,
    evidence_file VARCHAR(255) DEFAULT NULL,
    actual_time_impact_days INT DEFAULT NULL,
    convert_to_knowledge BOOLEAN DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Membuat tabel KEDUA: data_proyek_risk
CREATE TABLE IF NOT EXISTS data_proyek_risk (
    id VARCHAR(50) NOT NULL,
    timestamp DATETIME NOT NULL,
    risk_id VARCHAR(50) DEFAULT NULL,
    risk_identification_date DATE DEFAULT NULL,
    risk_owner_id VARCHAR(50) DEFAULT NULL,
    wbs_code VARCHAR(50) DEFAULT NULL,
    activity_name VARCHAR(255) DEFAULT NULL,
    critical_activity BOOLEAN DEFAULT NULL,
    bim_object_id VARCHAR(50) DEFAULT NULL,
    bim_element_name VARCHAR(50) DEFAULT NULL,
    risk_location VARCHAR(50) DEFAULT NULL,
    risk_category VARCHAR(50) DEFAULT NULL,
    risk_subcategory VARCHAR(50) DEFAULT NULL,
    risk_event TEXT DEFAULT NULL,
    risk_cause TEXT DEFAULT NULL,
    risk_impact_description TEXT DEFAULT NULL,
    change_trigger_potential VARCHAR(50) DEFAULT NULL,
    probability_score INT DEFAULT NULL,
    risk_score INT DEFAULT NULL,
    risk_level VARCHAR(50) DEFAULT NULL,
    risk_priority VARCHAR(50) DEFAULT NULL,
    mitigation_status VARCHAR(50) DEFAULT NULL,
    mitigation_plan TEXT DEFAULT NULL,
    mitigation_owner_id VARCHAR(50) DEFAULT NULL,
    mitigation_due_date DATE DEFAULT NULL,
    mitigation_cost DECIMAL(21,2) DEFAULT NULL,
    residual_probability INT DEFAULT NULL,
    residual_impact INT DEFAULT NULL,
    residual_risk_score INT DEFAULT NULL,
    early_warning_rule TEXT DEFAULT NULL,
    risk_status VARCHAR(50) DEFAULT NULL,
    generate_cr BOOLEAN DEFAULT NULL,
    linked_cr_id VARCHAR(50) DEFAULT NULL,
    related_knowledge_id VARCHAR(50) DEFAULT NULL,
    preventive_recommendation TEXT DEFAULT NULL,
    risk_evidence VARCHAR(255) DEFAULT NULL,
    monitoring_notes TEXT DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Membuat tabel KETIGA: data_proyek_kb
CREATE TABLE IF NOT EXISTS data_proyek_kb (
    id VARCHAR(50) NOT NULL,
    timestamp DATETIME NOT NULL,
    knowledge_id VARCHAR(50) DEFAULT NULL,
    knowledge_title VARCHAR(255) DEFAULT NULL,
    project_id VARCHAR(50) DEFAULT NULL,
    project_name VARCHAR(255) DEFAULT NULL,
    source_type VARCHAR(50) DEFAULT NULL,
    cr_id VARCHAR(50) DEFAULT NULL,
    risk_id VARCHAR(50) DEFAULT NULL,
    wbs_code VARCHAR(50) DEFAULT NULL,
    activity_name VARCHAR(255) DEFAULT NULL,
    bim_object_id VARCHAR(50) DEFAULT NULL,
    bim_element VARCHAR(50) DEFAULT NULL,
    change_category VARCHAR(50) DEFAULT NULL,
    risk_category VARCHAR(50) DEFAULT NULL,
    keywords TEXT DEFAULT NULL,
    problem_summary TEXT DEFAULT NULL,
    root_cause TEXT DEFAULT NULL,
    case_chronology TEXT DEFAULT NULL,
    time_impact INT DEFAULT NULL,
    cost_impact DECIMAL(21,2) DEFAULT NULL,
    quality_impact VARCHAR(50) DEFAULT NULL,
    risk_impact VARCHAR(50) DEFAULT NULL,
    critical_path_impact VARCHAR(50) DEFAULT NULL,
    decision_taken TEXT DEFAULT NULL,
    technical_solution TEXT DEFAULT NULL,
    mitigation_action TEXT DEFAULT NULL,
    implementation_result TEXT DEFAULT NULL,
    solution_effectiveness VARCHAR(50) DEFAULT NULL,
    effectiveness_notes TEXT DEFAULT NULL,
    lesson_learned TEXT DEFAULT NULL,
    preventive_recommendation TEXT DEFAULT NULL,
    reuse_condition TEXT DEFAULT NULL,
    similarity_criteria TEXT DEFAULT NULL,
    knowledge_type VARCHAR(50) DEFAULT NULL,
    seci_category VARCHAR(50) DEFAULT NULL,
    validation_status VARCHAR(50) DEFAULT NULL,
    validation_id VARCHAR(50) DEFAULT NULL,
    validation_notes TEXT DEFAULT NULL,
    validation_date DATE DEFAULT NULL,
    supporting_document VARCHAR(255) DEFAULT NULL,
    version VARCHAR(20) DEFAULT NULL,
    retrieval_count INT DEFAULT NULL,
    reused_in_cr_id VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;